server:
  port: 8088
restart:
  include:
    mapper: /mapper-[\\w-\\.]+jar
    pagehelper: /pagehelper-[\\w-\\.]+jar
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#
logging:
  level:
    root: info
    org.springframework: info
    org.springframework.jdbc: debug
    org.springframework.boot: info
    org.mybatis: debug
    com.alibaba.druid: debug
    com.github.trang: debug
    com.sdgc.demo: debug

spring:
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
    disable-html-escaping: true

  application:
    name: druid-spring-boot-jpa-example
  profiles:
    # 默认环境为 default，多数据源演示请改为 dynamic
    # active: dynamic
    active: default
  h2:
    console:
      enabled: true
      settings:
        trace: true
  datasource:
    #    #脚本引用
    #    #schema: import.sql
    #    #mysql 8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
#      username: root
#      password: root
#      maxActive: 20
#      initialSize: 1
#      max-wait: 30000
#      minIdle: 1
#      query-timeout: 10
#      validation-query: SELECT 1
#      use-global-data-source-stat: true
#
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 30000
#
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
#      asyncInit: true
db:
  conn:
    str:
      useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLocalSessionState=true&tinyInt1isBit=falses?serverTimezone=Asia/Shanghai
  datasource:
    db1:
      jdbc-url:
        jdbc: jdbc:mysql://localhost:3306/test?${db.conn.str}
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    db2:
      jdbc-url:
        jdbc: jdbc:mysql://localhost:3306/test?${db.conn.str}
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver





#      # 默认开启，当前已开启
#      # 默认关闭，需手动开启，当前已关闭
#      stat-view-servlet:
#        enabled: false
#     # stat-logger: false
#      filter:
#        # 默认关闭，需手动开启，当前已开启
#        slf4j:
#          enabled: true
#          data-source-log-enabled: false
#          connection-log-enabled: false
#          statement-log-enabled: false
#          result-set-log-enabled: false
#            # 默认关闭，需手动开启，当前已开启
#        wall:
#          enabled: true
#          log-violation: true
#          throw-exception: false
#          config:
#            delete-where-none-check: true
#        stat:
#          log-slow-sql: true
#          slow-sql-millis: 1000
#        # 默认关闭，需手动开启，当前已关闭
#        config:
#          enabled: false
#        # 默认关闭，需手动开启，当前已关闭
#        web-stat:
#          enabled: false
#        # 默认关闭，需手动开启，当前已关闭
#
#        aop-stat:
#          enabled: false
#      db-type: mysql
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#  #事务
#  transaction:
#    rollback-on-commit-failure: true
#  mvc:
#    servlet:
#      load-on-startup: 1
#  aop:
#    auto: true
#    proxy-target-class: true
#  http:
#    encoding:
#      enabled: true
#      force: true
#      charset: utf-8
#    converters:
#      preferred-json-mapper: jackson
#  jackson:
#    default-property-inclusion: non_null
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#    serialization:
#      indent_output: true
#      write_null_map_values: true
#      write_dates_as_timestamps: false
#    deserialization:
#      fail_on_unknown_properties: false
#    parser:
#      allow_unquoted_control_chars: true
#      allow_single_quotes: true
#
#---
#
#debug: true
#
#spring:
#  profiles: dynamic
#  autoconfigure:
#    exclude:
#      # 多数据源场景会导致 `javax.sql.DataSource` 和 `org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer`
#      # 循环依赖，所以需要手动排除 `org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration`
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  datasource:
#    schema: classpath:import.sql
#    druid:
#      # 继承 spring.datasource.druid 前缀的配置，同时可以自定义配置，若名称相同则覆盖父配置
#      data-sources:
#        master:
#          url: jdbc:h2:mem:master
#          max-active: 50
#          max-open-prepared-statements: 50
#        slave:
#          url: jdbc:h2:mem:slave
#          max-active: 25
#          max-open-prepared-statements: 25
