spring:
  profiles:
    active: dev

---
server:
  port: 9999
  servlet:
    context-path: /
spring:
  profiles: dev

  # 邮箱服务器地址
  mail:
    host: smtp.qq.com
    username: 1421504642@qq.com
    password: mbsaflnrrnwefiea
    default-encoding: UTF-8

  application:
    name: sedin-external-spring-boot
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://172.18.2.207:3306/office?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validation-query: SELECT 1 #对于数据库连接的检测
      test-while-idle: true #如果空闲时间大于time-between-eviction-runs-millis 使用validation-query检测连接是否有效，无效则淘汰
      test-on-borrow: false #申请连接时检测连接是否有效 影响性能关闭
      filters: stat,wall,config
      ##### WebStatFilter配置 #######
      web-stat-filter:
        #启用StatFilter
        enabled: true
        #添加过滤规则
        url-pattern: /*
        #排除一些不必要的url
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        #开启session统计功能
        session-stat-enable: true
        #缺省sessionStatMaxCount是1000个
        session-stat-max-count: 1000
      filter:
#        slf4j:
#          enabled: true
#          result-set-log-enabled: false
#          statement-create-after-log-enabled: false
#          statement-close-after-log-enabled: false
#          result-set-open-after-log-enabled: false
#          result-set-close-after-log-enabled: false
#          result-set-log-error-enabled: false
#          result-set-next-after-log-enabled: false
        log4j2:
          statement-sql-pretty-format: false
          enabled: true
          result-set-log-enabled: false
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: true
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: true
          result-set-log-error-enabled: false
          result-set-next-after-log-enabled: false


  gson:
    #    是否序列化空值
    serialize-nulls: off
    #    禁用html转义
    disable-html-escaping: true
    #    日期格式
    date-format: yyyy-MM-dd hh:mm:ss
    #    禁用内部类的序列化
    disable-inner-class-serialization: true
    #    启用复杂映射键序列化
    enable-complex-map-key-serialization: true
    #    排除没有注释的字段
    exclude-fields-without-expose-annotation: true
    #    现场命名策略
    field-naming-policy: identity
    #    生成不可执行的json
    generate-non-executable-json: true
    #    宽容
    lenient: true
    #    长期串行化政策
    long-serialization-policy: string
    #    漂亮印刷
    pretty-printing: true

logging:
  level:
    com.burst.sedin: DEBUG
    jdbc.sqltiming: DEBUG
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.mybatisplus.demo.entity
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*Dao.xml
  global-config:
    banner: false
---
server:
  port: 9999
  servlet:
    context-path: /
spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.2.207:3306/office?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  level:
    com.mybatisplus.demo: DEBUG
    jdbc.sqltiming: DEBUG
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*Dao.xml
